# Generated by Django 4.2.4 on 2023-08-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-updated_at']},
        ),
    ]
