# Generated by Django 4.2.4 on 2023-08-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('identity_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('identity_number', models.CharField(max_length=50, unique=True)),
                ('kra_pin', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_number', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('DELAYED', 'Delayed'), ('ON WAY', 'On way'), ('ARRIVED', 'Arrived')], default='ON WAY', max_length=255)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('recipient_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=250, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=250, null=True)),
                ('engine_size', models.CharField(blank=True, max_length=250, null=True)),
                ('engine_power', models.CharField(blank=True, max_length=250, null=True)),
                ('yom', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('DELAYED', 'Delayed'), ('ON WAY', 'On way'), ('ARRIVED', 'Arrived')], default='ON WAY', max_length=255)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('parcels', models.ManyToManyField(to='core.parcel')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
