# Generated by Django 4.2.4 on 2023-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='chasis_number',
            field=models.CharField(default='g', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(default='g', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
