# Generated by Django 4.2.4 on 2023-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_truck_chasis_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
        migrations.AddField(
            model_name='truck',
            name='carry_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='parcels',
            field=models.ManyToManyField(blank=True, to='core.parcel'),
        ),
    ]
