# Generated by Django 4.2.4 on 2023-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_shipment_destination_shipment_route_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='a', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
